print("What are your 10 numbers?")
print("First Number:")
one = int(input())
print("Second Number:")
two = int(input())
print("Third Number:")
three = int(input())
print("Four Number:")
four = int(input())
print("Fifth Number:")
five = int(input())
print("Sixth Number:")
six = int(input())
print("Seventh Number:")
seven = int(input())
print("Eighth Number:")
eight = int(input())
print("Ninth Number:")
nine = int(input())
print("Tenth Number:")
ten = int(input())

numbers = [one, two, three, four, five, six, seven, eight, nine, ten]
numbers = sum(numbers)

print(numbers)
