# Display ascii art
print("(0 | 0) \n   O \n  -O- \n   O \n  ! !")
print("Please now customize the robot")
print("Please enter a character for the robot eyes")
eyes = input()
print("Please enter a character for the robot hands")
hands = input()
print("Please enter a character for the robot legs")
legs = input()
print("(",eyes,"|",eyes,")")
print("    O ")
print(" ",hands,"O",hands)
print("    O ")
print("  ",legs,legs)
